package euler;

public class Problem2 {
/*********************************************************************************
Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2, the first 10 terms will be:

1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...

By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.
*********************************************************************************/
	public void run(){
		int a = 0, b = 2, sum = 2;
		while(b < 4000000){
			int temp = (b * 4) + a;
			a = b;
			b = temp;
			sum += b < 4000000 ? b : 0;
		}
		System.out.println("Sum: " + Integer.toString(sum));
	}
}
